[package]
name = "yafetch"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
fs2 = "0.4.3"
machine-info = "1.0.9"
mlua = { version = "0.9.1", features = ["lua54", "vendored"] }
sysinfo = "0.30.5"
systemstat = "0.2.3"
xdg = "2.5.2"
